/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HubRouteImport } from './routes/hub'
import { Route as GuaranteesRouteImport } from './routes/guarantees'
import { Route as FormatsRouteImport } from './routes/formats'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as FormatsSlugRouteImport } from './routes/formats.$slug'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesRoute = GuaranteesRouteImport.update({
  id: '/guarantees',
  path: '/guarantees',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsRoute = FormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsSlugRoute = FormatsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FormatsRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompaniesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/benchmarks': typeof BenchmarksRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/docs': typeof DocsRoute
  '/formats': typeof FormatsRouteWithChildren
  '/guarantees': typeof GuaranteesRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/benchmarks': typeof BenchmarksRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/docs': typeof DocsRoute
  '/formats': typeof FormatsRouteWithChildren
  '/guarantees': typeof GuaranteesRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/benchmarks': typeof BenchmarksRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/docs': typeof DocsRoute
  '/formats': typeof FormatsRouteWithChildren
  '/guarantees': typeof GuaranteesRoute
  '/hub': typeof HubRoute
  '/login': typeof LoginRoute
  '/personas': typeof PersonasRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/use-cases': typeof UseCasesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/formats/$slug': typeof FormatsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/benchmarks'
    | '/companies'
    | '/docs'
    | '/formats'
    | '/guarantees'
    | '/hub'
    | '/login'
    | '/personas'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/blog/$slug'
    | '/companies/$slug'
    | '/formats/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/app'
    | '/benchmarks'
    | '/companies'
    | '/docs'
    | '/formats'
    | '/guarantees'
    | '/hub'
    | '/login'
    | '/personas'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/blog/$slug'
    | '/companies/$slug'
    | '/formats/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/benchmarks'
    | '/companies'
    | '/docs'
    | '/formats'
    | '/guarantees'
    | '/hub'
    | '/login'
    | '/personas'
    | '/pricing'
    | '/signup'
    | '/use-cases'
    | '/blog/$slug'
    | '/companies/$slug'
    | '/formats/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRoute
  BenchmarksRoute: typeof BenchmarksRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DocsRoute: typeof DocsRoute
  FormatsRoute: typeof FormatsRouteWithChildren
  GuaranteesRoute: typeof GuaranteesRoute
  HubRoute: typeof HubRoute
  LoginRoute: typeof LoginRoute
  PersonasRoute: typeof PersonasRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  UseCasesRoute: typeof UseCasesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees': {
      id: '/guarantees'
      path: '/guarantees'
      fullPath: '/guarantees'
      preLoaderRoute: typeof GuaranteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats': {
      id: '/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats/$slug': {
      id: '/formats/$slug'
      path: '/$slug'
      fullPath: '/formats/$slug'
      preLoaderRoute: typeof FormatsSlugRouteImport
      parentRoute: typeof FormatsRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesSlugRoute: typeof CompaniesSlugRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesSlugRoute: CompaniesSlugRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface FormatsRouteChildren {
  FormatsSlugRoute: typeof FormatsSlugRoute
}

const FormatsRouteChildren: FormatsRouteChildren = {
  FormatsSlugRoute: FormatsSlugRoute,
}

const FormatsRouteWithChildren =
  FormatsRoute._addFileChildren(FormatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRoute,
  BenchmarksRoute: BenchmarksRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DocsRoute: DocsRoute,
  FormatsRoute: FormatsRouteWithChildren,
  GuaranteesRoute: GuaranteesRoute,
  HubRoute: HubRoute,
  LoginRoute: LoginRoute,
  PersonasRoute: PersonasRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  UseCasesRoute: UseCasesRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
