export type Post = {
  slug: string;
  tag: string;
  read: number;
  title: { fr: string; en: string };
  summary: { fr: string; en: string };
  schemas: Array<"quantization" | "distillation" | "pruning" | "ffmpeg">;
  body: { fr: string[]; en: string[] };
};

const P = (
  slug: string,
  tag: string,
  read: number,
  titleFr: string,
  titleEn: string,
  summaryFr: string,
  summaryEn: string,
  schemas: Post["schemas"],
  bodyFr: string[],
  bodyEn: string[],
): Post => ({
  slug,
  tag,
  read,
  title: { fr: titleFr, en: titleEn },
  summary: { fr: summaryFr, en: summaryEn },
  schemas,
  body: { fr: bodyFr, en: bodyEn },
});

export const POSTS: Post[] = [
  P("pourquoi-conversion-cassee", "État de l'art", 9,
    "Pourquoi la conversion de modèles IA est cassée",
    "Why AI model conversion is broken",
    "Trois symptômes structurels : fragmentation, perte silencieuse, scripts jetables. Voici pourquoi UMC existe.",
    "Three structural symptoms: fragmentation, silent loss, throwaway scripts. Why UMC exists.",
    ["ffmpeg"],
    [
      "En 2025, déployer un modèle IA reste un cauchemar logistique. Un modèle entraîné en PyTorch sur GPU NVIDIA doit pouvoir tourner sur iPhone (CoreML), sur NPU Qualcomm (QNN), sur CPU Intel (OpenVINO) et dans un navigateur (ONNX Runtime Web). Chaque cible exige un format différent, des outils différents, des versions différentes — et aucune garantie que la sortie est identique au modèle d'origine.",
      "Premier symptôme : la fragmentation. Trente-deux formats principaux coexistent, créés par des acteurs concurrents. Aucun n'est neutre. Chacun est conçu pour verrouiller un matériel.",
      "Deuxième symptôme : la perte silencieuse. Une conversion FP32 → INT4 peut faire chuter la précision MMLU de 12 points sans qu'aucun outil ne le détecte. Les équipes déploient des modèles dégradés en production sans le savoir.",
      "Troisième symptôme : les scripts jetables. Chaque équipe ML maintient ses propres pipelines Python — non testés, non documentés, cassés à la première mise à jour de torch ou transformers.",
      "UMC répond aux trois : un service universel, une certification cryptographique, une garantie de reproductibilité (un certificat ed25519 par conversion).",
    ],
    [
      "In 2025, shipping an AI model is still a logistics nightmare. A model trained in PyTorch on NVIDIA GPUs must run on iPhone (CoreML), Qualcomm NPUs (QNN), Intel CPUs (OpenVINO) and in browsers. Each target needs a different format, different tools, different versions — no guarantee the output matches the source.",
      "First symptom: fragmentation. Thirty-two main formats coexist, built by competing vendors. None is neutral. Every one is designed to lock in hardware.",
      "Second symptom: silent loss. A FP32 → INT4 conversion can drop MMLU by 12 points with no tool catching it. Teams ship degraded models without knowing.",
      "Third symptom: throwaway scripts. Every ML team maintains its own Python pipelines — untested, undocumented, broken on the next torch update.",
      "UMC answers all three: a universal service, cryptographic certification, reproducibility guarantee (one ed25519 certificate per conversion).",
    ]),
  P("ffmpeg-des-modeles-ia", "Analogie", 8,
    "UMC est le ffmpeg des modèles IA",
    "UMC is the ffmpeg of AI models",
    "Le parallèle historique qui explique tout le projet : pourquoi un standard universel est inévitable.",
    "The historical parallel that explains the whole project: why a universal standard is inevitable.",
    ["ffmpeg"],
    [
      "En 2000, la vidéo numérique était fragmentée : plus de 100 codecs incompatibles, chaque éditeur publiait son propre format pour verrouiller son lecteur et son matériel.",
      "ffmpeg a brisé ce monopole. Un seul outil capable de lire et d'écrire n'importe quel format. YouTube, Netflix, le web vidéo entier en dépendent aujourd'hui.",
      "L'IA vit exactement la même fragmentation en 2025 : 32 formats principaux, chaque acteur verrouille son matériel via son format.",
      "UMC joue le rôle de ffmpeg pour les modèles IA : un service neutre capable de convertir entre tous les formats avec garantie cryptographique de zéro perte.",
      "Pourquoi cela compte ? Parce qu'un modèle entraîné sur GPU NVIDIA doit pouvoir tourner sur iPhone, sur NPU Qualcomm, sur CPU Intel, sans réentraînement.",
    ],
    [
      "In 2000 digital video was fragmented: 100+ incompatible codecs, every vendor shipped its own format to lock in its player and hardware.",
      "ffmpeg broke that monopoly. One tool able to read and write any format. YouTube, Netflix and the entire video web rely on it today.",
      "AI lives the exact same fragmentation in 2025: 32 main formats, each vendor locks its hardware via its format.",
      "UMC plays the ffmpeg role for AI models: a neutral service able to convert between every format with a cryptographic guarantee of zero loss.",
      "Why does it matter? Because a model trained on NVIDIA GPU must be deployable on iPhone, Qualcomm NPU, Intel CPU — without retraining.",
    ]),
  P("32-formats-explique", "Guide", 22,
    "Les 32 formats de modèles IA, expliqués simplement",
    "The 32 AI model formats, explained simply",
    "Référence visuelle complète : créateur, matériel cible, raisons d'exister.",
    "Complete visual reference: creator, target hardware, reasons to exist.",
    ["ffmpeg"],
    [
      "L'écosystème se découpe en quatre familles : stockage (SafeTensors, PyTorch, GGUF), inférence GPU datacenter (TensorRT, TensorRT-LLM, vLLM), edge & mobile (CoreML, TFLite, ExecuTorch, NCNN, MNN, RKNN, QNN), et formats neutres d'échange (ONNX, MLIR).",
      "Chaque format a été créé pour une raison stratégique : verrouiller un matériel, optimiser une plateforme, ou casser un monopole.",
      "UMC parle les 32 et certifie chaque conversion. La page /formats détaille chacun : créateur, année, matériel cible, raison d'exister, entreprises utilisatrices.",
      "Formats émergents à surveiller : FP8 (Hopper/Blackwell), WebNN (W3C), MLX (Apple Silicon), MindSpore (Huawei Ascend). Tous supportés par UMC dès leur sortie.",
    ],
    [
      "The ecosystem splits in four families: storage, datacenter GPU inference, edge & mobile, neutral exchange.",
      "Every format was built for a strategic reason: lock in hardware, optimize a platform, or break a monopoly.",
      "UMC speaks all 32 and certifies every conversion. The /formats page details each: creator, year, target hardware, reason to exist, companies that use it.",
      "Emerging formats to watch: FP8, WebNN, MLX, MindSpore. All supported by UMC at release.",
    ]),
  P("quantification-expliquee", "Quantification", 15,
    "Guide complet de la quantification (Q4_K_M, AWQ, GPTQ, FP8)",
    "Complete quantization guide (Q4_K_M, AWQ, GPTQ, FP8)",
    "Compresser un modèle de 16 à 4 bits sans le casser. Schéma, méthodes, benchmarks.",
    "Compress a model from 16 to 4 bits without breaking it.",
    ["quantization"],
    [
      "Quantifier un modèle, c'est représenter chaque poids avec moins de bits. FP32 (4 octets) → FP16 (2) → INT8 (1) → INT4 (0,5).",
      "Le gain est triple : taille divisée par 8, RAM réduite d'autant, calcul plus rapide grâce aux instructions matérielles dédiées (Tensor Cores, NEON, AVX-512).",
      "Q4_K_M garde 4 bits pour les poids ordinaires et 6 bits pour les poids sensibles identifiés par llama.cpp.",
      "AWQ observe les activations sur un dataset de calibration et protège les colonnes de poids saillantes.",
      "GPTQ optimise quant par quant via la matrice Hessienne approximée. Idéal pour les GPU NVIDIA.",
      "FP8 (E4M3, E5M2) est le nouveau standard sur Hopper et Blackwell : divise la mémoire par 2 sans perte mesurable.",
      "Recommandation : INT8 pour la production serveur, Q4_K_M pour l'inférence locale, FP8 pour l'entraînement H100+, Q2_K pour les modèles embarqués.",
    ],
    [
      "Quantizing means representing each weight with fewer bits. FP32 (4 B) → FP16 (2) → INT8 (1) → INT4 (0.5).",
      "Triple win: size /8, RAM reduced, faster compute via dedicated hardware instructions.",
      "Q4_K_M keeps 4 bits for ordinary weights and 6 bits for salient weights flagged by llama.cpp.",
      "AWQ observes activations on a calibration dataset and protects salient weight columns.",
      "GPTQ optimizes step-by-step via approximated Hessian. Ideal on NVIDIA GPUs.",
      "FP8 (E4M3, E5M2) is the new standard on Hopper and Blackwell: halves memory with no measurable loss.",
      "Recommendation: INT8 for server prod, Q4_K_M for local, FP8 for H100+ training, Q2_K for embedded.",
    ]),
  P("lora-qlora", "Fine-tuning", 11,
    "LoRA et QLoRA : comment les adaptateurs fonctionnent",
    "LoRA and QLoRA: how adapters work",
    "Spécialiser un LLM 70B avec 50 Mo de poids supplémentaires.",
    "Specialize a 70B LLM with 50 MB of extra weights.",
    [],
    [
      "LoRA (Low-Rank Adaptation) repose sur une observation : la mise à jour ΔW lors d'un fine-tune est de très faible rang. On l'approxime par B·A avec r ≪ d.",
      "Concrètement : au lieu d'apprendre les 70 milliards de poids d'un Llama 3, on apprend uniquement A et B pour chaque couche d'attention. Le coût mémoire chute de 99,9%.",
      "QLoRA pousse plus loin : on charge le modèle de base en 4-bit (NF4), on gèle ses poids, on entraîne les adaptateurs en FP16. Un Llama 3 70B se fine-tune sur une seule RTX 4090.",
      "Côté déploiement, UMC exporte les adaptateurs LoRA séparément (un .safetensors de 30–100 Mo) ou fusionnés. vLLM, TGI, llama.cpp gèrent le hot-swap : un seul modèle de base sert des dizaines de tâches.",
    ],
    [
      "LoRA (Low-Rank Adaptation) relies on one fact: the matrix update ΔW during fine-tuning has very low rank. Approximate it with B·A where r ≪ d.",
      "Concretely: instead of learning Llama 3's 70 billion weights, you learn only A and B per attention layer. Memory cost drops by 99.9%.",
      "QLoRA goes further: load the base in 4-bit (NF4), freeze its weights, train the adapters in FP16. Llama 3 70B fine-tunes on a single RTX 4090.",
      "For deployment, UMC exports LoRA adapters separately (30–100 MB .safetensors) or merged. vLLM, TGI, llama.cpp support hot-swap: one base model serves dozens of tasks.",
    ]),
  P("distillation-expliquee", "Distillation", 12,
    "Distillation de connaissance expliquée",
    "Knowledge distillation explained",
    "Comment un student 7B hérite de presque toute la qualité d'un teacher 70B.",
    "How a 7B student inherits nearly all the quality of a 70B teacher.",
    ["distillation"],
    [
      "La distillation entraîne un petit modèle (student) à imiter les sorties d'un grand modèle (teacher). Au lieu de labels durs, le student apprend les probabilités complètes : les soft labels.",
      "Ces soft labels portent une information bien plus riche. Si le teacher hésite entre chat (60%) et chien (30%), le student apprend cette nuance.",
      "Résultat : un modèle 10× plus petit peut atteindre 95% de la qualité du teacher. Mistral, Phi-3, Gemma 2 ont été construits ainsi.",
      "Distillation et quantification se combinent : on distille puis on quantifie le student. Ratio compression/qualité jusqu'à 50× avec moins de 3 points sur MMLU.",
    ],
    [
      "Distillation trains a small student to mimic a large teacher. Instead of hard labels, the student learns full probability distributions: the soft labels.",
      "Soft labels carry far more information. If the teacher hesitates between cat (60%) and dog (30%), the student learns that nuance.",
      "Outcome: a model 10× smaller can reach 95% of teacher quality. Mistral, Phi-3, Gemma 2 were built this way.",
      "Distillation and quantization combine: distill first, then quantize. Ratios up to 50× with less than 3 points lost on MMLU.",
    ]),
  P("elagage-pruning", "Élagage", 9,
    "Élagage (pruning) : couper le superflu",
    "Pruning: cutting the dead weight",
    "Jusqu'à 50% des connexions d'un réseau sont inutiles.",
    "Up to 50% of a network's connections are useless.",
    ["pruning"],
    [
      "L'élagage supprime les poids dont la valeur absolue est très petite. Sur un Transformer typique, on retire 30 à 50% des poids avec moins de 1 point de perte.",
      "Deux variantes : structuré (têtes d'attention, couches → vrai gain de vitesse) et non structuré (poids individuels → gain mémoire).",
      "UMC supporte l'élagage structuré comme étape de pipeline : entraînement → élagage → fine-tuning court → quantification → export GGUF/CoreML.",
    ],
    [
      "Pruning removes weights with very small absolute value. On a typical Transformer you can drop 30–50% of weights for less than 1 point lost.",
      "Two flavors: structured (attention heads, layers → real speedup) and unstructured (individual weights → memory gain).",
      "UMC supports structured pruning as a pipeline step: training → pruning → short fine-tune → quantization → export.",
    ]),
  P("pourquoi-umc-meilleur", "Produit", 7,
    "Pourquoi UMC est le meilleur convertisseur",
    "Why UMC is the best converter",
    "Cinq garanties que personne d'autre n'offre.",
    "Five guarantees nobody else offers.",
    [],
    [
      "Garantie 1 — Précision bornée : chaque conversion mesure la divergence δ tenseur par tenseur. Pour F32 → F16, δ < 1e-6 est garanti contractuellement.",
      "Garantie 2 — Certificat ed25519 : chaque sortie est signée. L'auditeur peut vérifier que le binaire déployé correspond bien au modèle source.",
      "Garantie 3 — Streaming mmap : UMC convertit un modèle de 810 Go avec seulement 800 Mo de RAM.",
      "Garantie 4 — Vitesse : Llama 3.1 8B GGUF → ONNX en 4,2 s, contre 12 s pour llama.cpp et 47 s pour transformers.",
      "Garantie 5 — Couverture : 32 formats, 280+ chemins certifiés. Aucun autre outil ne dépasse 6.",
    ],
    [
      "Guarantee 1 — Bounded precision: every conversion measures δ tensor-by-tensor. For F32 → F16, δ < 1e-6 is contractually guaranteed.",
      "Guarantee 2 — ed25519 certificate: every output is signed. Auditors can verify the deployed binary matches the source.",
      "Guarantee 3 — mmap streaming: UMC converts an 810 GB model with only 800 MB of RAM.",
      "Guarantee 4 — Speed: Llama 3.1 8B GGUF → ONNX in 4.2 s, vs 12 s for llama.cpp and 47 s for transformers.",
      "Guarantee 5 — Coverage: 32 formats, 280+ certified paths. No other tool exceeds 6.",
    ]),
  P("zero-loss-garantie", "Garanties", 10,
    "Comment UMC garantit zéro perte d'information",
    "How UMC guarantees zero information loss",
    "Round-trip vérifié sur tous les tenseurs, fingerprint SHA-256, divergence bornée.",
    "Round-trip verified on every tensor, SHA-256 fingerprint, bounded divergence.",
    [],
    [
      "Pour chaque conversion lossless (F32 ↔ F16 ↔ BF16, SafeTensors ↔ PyTorch ↔ GGUF), UMC effectue un round-trip et compare octet par octet.",
      "Pour les conversions lossy contrôlées (quantification), UMC mesure δ_max sur chaque tenseur. Si la divergence dépasse le seuil, la conversion échoue.",
      "Chaque tenseur d'entrée et de sortie a un fingerprint SHA-256 stocké dans le certificat ed25519. Reproductibilité totale.",
    ],
    [
      "For lossless conversions, UMC performs a round-trip and compares byte-by-byte.",
      "For controlled lossy conversions, UMC measures δ_max per tensor. Above threshold → conversion fails.",
      "Every tensor has a SHA-256 fingerprint stored in the ed25519 certificate. Full reproducibility.",
    ]),
  P("installer-umc", "Installation", 6,
    "Comment installer UMC concrètement (Linux, macOS, Windows, Docker)",
    "How to install UMC concretely",
    "Service en ligne sans installation, ou binaire local et Docker pour l'usage avancé.",
    "Online service, or local binary and Docker for advanced use.",
    [],
    [
      "Option 1 — Service en ligne (recommandé) : aucune installation, ouvrez l'atelier, glissez votre fichier, téléchargez le résultat.",
      "Option 2 — Binaire local : curl -fsSL umc.dev/install.sh | sh installe le binaire dans /usr/local/bin. Linux x86_64/arm64, macOS Intel/Apple Silicon.",
      "Option 3 — Windows : téléchargez l'installateur .msi ou utilisez winget install umc.",
      "Option 4 — Docker : docker run --rm -v $PWD:/io ghcr.io/umc/cli convert /io/model.safetensors --to gguf. Image multi-arch, ≈ 80 Mo.",
      "Option 5 — CI/CD : GitHub Action umc-org/setup-umc@v1 ajoute le binaire au PATH.",
    ],
    [
      "Option 1 — Online service (recommended): zero install, open the workshop, drop your file, download the result.",
      "Option 2 — Local binary: curl -fsSL umc.dev/install.sh | sh drops the binary in /usr/local/bin.",
      "Option 3 — Windows: download the .msi installer or use winget install umc.",
      "Option 4 — Docker: docker run --rm -v $PWD:/io ghcr.io/umc/cli convert /io/model.safetensors --to gguf.",
      "Option 5 — CI/CD: GitHub Action umc-org/setup-umc@v1 adds the binary to PATH.",
    ]),
  P("deployer-iphone-coreml", "Déploiement", 8,
    "Déployer un modèle sur iPhone avec CoreML via UMC",
    "Deploy a model on iPhone with CoreML via UMC",
    "Convertir un Phi-3 mini en CoreML quantifié et l'embarquer dans une app Swift en 10 minutes.",
    "Convert a Phi-3 mini to quantized CoreML and embed it in a Swift app in 10 minutes.",
    [],
    [
      "Étape 1 — Conversion : ouvrez l'atelier, glissez Phi-3-mini.safetensors, choisissez CoreML INT4. UMC produit un .mlpackage de 1,8 Go en ≈ 9 s.",
      "Étape 2 — Inspection : umc inspect phi3-mini.mlpackage confirme l'architecture, 32 couches, tokenizer SentencePiece embarqué.",
      "Étape 3 — Intégration Xcode : glissez le .mlpackage dans votre projet Xcode 15+. Le compilateur génère les classes Swift typées.",
      "Étape 4 — Inférence Swift : MLModel(contentsOf: url), créez un prédicteur, envoyez les tokens. Le Neural Engine fait le reste — 18 tok/s sur iPhone 15 Pro.",
      "Étape 5 — Confidentialité : aucun appel réseau, aucune fuite de prompt, conformité RGPD native.",
    ],
    [
      "Step 1 — Convert: open workshop, drop Phi-3-mini.safetensors, pick CoreML INT4. UMC ships a 1.8 GB .mlpackage in ≈ 9 s.",
      "Step 2 — Inspect: umc inspect confirms architecture, 32 layers, embedded SentencePiece tokenizer.",
      "Step 3 — Xcode: drag the .mlpackage into your Xcode 15+ project. Auto-generated typed Swift classes.",
      "Step 4 — Swift inference: MLModel(contentsOf: url), create a predictor, feed tokens. Neural Engine handles the rest — 18 tok/s on iPhone 15 Pro.",
      "Step 5 — Privacy: zero network, zero prompt leakage, native GDPR.",
    ]),
  P("tensorrt-3-commandes", "Performance", 7,
    "Optimiser pour NVIDIA TensorRT en 3 commandes",
    "Optimize for NVIDIA TensorRT in 3 commands",
    "Du SafeTensors au moteur TensorRT-LLM compilé pour H100, certifié, en moins d'une minute.",
    "From SafeTensors to a certified TensorRT-LLM engine for H100 in under a minute.",
    [],
    [
      "Commande 1 — umc convert llama3.safetensors --to onnx --opset 19. ONNX valide en ≈ 7 s via mmap.",
      "Commande 2 — umc convert llama3.onnx --to tensorrt-llm --gpu H100 --precision fp8. Moteur .engine optimisé.",
      "Commande 3 — umc verify llama3.engine --against llama3.safetensors --tolerance 1e-3. Certificat émis.",
      "Résultat : Llama 3 70B servi à 4 200 tokens/s sur 8× H100, vs ≈ 1 100 tokens/s avec vLLM seul.",
    ],
    [
      "Command 1 — umc convert llama3.safetensors --to onnx --opset 19. Valid ONNX in ≈ 7 s via mmap.",
      "Command 2 — umc convert llama3.onnx --to tensorrt-llm --gpu H100 --precision fp8. Optimized .engine.",
      "Command 3 — umc verify llama3.engine --against llama3.safetensors --tolerance 1e-3. Certificate issued.",
      "Result: Llama 3 70B served at 4,200 tokens/s on 8× H100, vs ≈ 1,100 tokens/s with vLLM alone.",
    ]),
  P("200go-800mo-ram", "Performance", 8,
    "Convertir un modèle de 200 Go avec 800 Mo de RAM",
    "Convert a 200 GB model with 800 MB of RAM",
    "Streaming mmap, pipeline parallèle, zero-copy.",
    "Mmap streaming, parallel pipeline, zero-copy.",
    [],
    [
      "Technique fondamentale : memory-mapping. Au lieu de charger 200 Go en RAM, UMC mappe le fichier dans l'espace d'adressage virtuel. L'OS pagine à la demande.",
      "Pipeline parallèle : UMC découpe la conversion en étages (lecture → transformation → écriture). Chaque étage sur un thread distinct, sur des chunks de 8 Mo.",
      "Zero-copy : les tenseurs ne sont jamais dupliqués. SafeTensors → GGUF : lecture, transformation en place, écriture.",
      "Résultat mesuré : Llama 3.1 405B (810 Go) converti en 4 min 12 s avec 800 Mo de RAM constants.",
    ],
    [
      "Core technique: memory-mapping. Instead of loading 200 GB into RAM, UMC maps the file in virtual address space. The OS pages on demand.",
      "Parallel pipeline: stages (read → transform → write) on dedicated threads, 8 MB chunks.",
      "Zero-copy: tensors are never duplicated. Read byte → transform in place → write.",
      "Measured: Llama 3.1 405B (810 GB) converted in 4 min 12 s with constant 800 MB of RAM.",
    ]),
  P("ia-act-tracabilite", "Compliance", 9,
    "UMC et la conformité EU AI Act",
    "UMC and EU AI Act compliance",
    "Chaque conversion produit une signature ed25519. Auditable, vérifiable, conforme.",
    "Every conversion produces an ed25519 signature. Auditable, verifiable, compliant.",
    [],
    [
      "L'EU AI Act impose à partir de 2026 une traçabilité complète des modèles déployés dans des contextes à haut risque.",
      "Chaque conversion UMC produit un certificat ed25519 : version exacte du source, hashes tensor par tensor, paramètres de conversion, divergence δ, horodatage signé.",
      "Le certificat est attaché au fichier converti et vérifiable hors-ligne avec n'importe quel outil ed25519 (openssl, libsodium).",
      "Un auditeur peut vérifier qu'un modèle déployé correspond bien au modèle d'origine, sans manipulation.",
    ],
    [
      "From 2026 the EU AI Act enforces full traceability of models in high-risk contexts.",
      "Every UMC conversion produces an ed25519 certificate: exact source version, per-tensor hashes, conversion params, measured δ, signed timestamp.",
      "The certificate is attached to the output and can be verified offline (openssl, libsodium).",
      "An auditor can verify a deployed model matches the original, untampered.",
    ]),
  P("cicd-github-actions", "DevOps", 7,
    "Intégrer UMC dans un pipeline CI/CD (GitHub Actions)",
    "Wire UMC into a CI/CD pipeline (GitHub Actions)",
    "Une action officielle, un job de validation à chaque commit, des certificats archivés.",
    "An official action, validation on every commit, archived certificates.",
    [],
    [
      "Étape 1 — Setup : umc-org/setup-umc@v1 installe le binaire en ≈ 4 s.",
      "Étape 2 — Convert : umc convert models/source.safetensors --to gguf --quant Q4_K_M --out artifacts/",
      "Étape 3 — Verify : umc verify artifacts/source.gguf --against models/source.safetensors. Si δ dépasse la tolérance, le job échoue.",
      "Étape 4 — Archive : actions/upload-artifact@v4 stocke le fichier converti ET son certificat. Audit trail.",
      "Étape 5 — Release : déclenchez une release GitHub quand le tag passe les checks. Binaire + certificat publiés ensemble.",
    ],
    [
      "Step 1 — Setup: umc-org/setup-umc@v1 installs the binary in ≈ 4 s.",
      "Step 2 — Convert: umc convert models/source.safetensors --to gguf --quant Q4_K_M --out artifacts/",
      "Step 3 — Verify: umc verify artifacts/source.gguf --against models/source.safetensors. Above tolerance → job fails.",
      "Step 4 — Archive: actions/upload-artifact@v4 stores converted file AND ed25519 certificate.",
      "Step 5 — Release: trigger a GitHub release when tag passes checks.",
    ]),
  P("formats-geants", "Histoire", 14,
    "Les formats créés par les géants : TensorRT, CoreML, TFLite, ExecuTorch",
    "Formats created by the giants: TensorRT, CoreML, TFLite, ExecuTorch",
    "Pourquoi NVIDIA, Apple, Google et Meta ont chacun créé leur format propriétaire.",
    "Why NVIDIA, Apple, Google and Meta each built their proprietary format.",
    [],
    [
      "NVIDIA TensorRT (2017) : ≈ 90 % du marché GPU datacenter. Compile par génération (Volta, Ampere, Hopper, Blackwell). Verrouillage matériel total.",
      "Apple CoreML (2017) : seul moyen d'exploiter le Neural Engine. Aucun export vers Android. Inférence privée on-device.",
      "Google TFLite (2017) : Android domine le mobile mondial. TFLite est optimisé ARM Cortex et Pixel TPU. Latence < 10 ms.",
      "Meta ExecuTorch (2024) : équipe Quest, Ray-Ban, futurs AR wearables. PyTorch on-device sans serveur cloud.",
      "Chacun a sa raison stratégique. UMC convertit entre tous, sans favoritisme.",
    ],
    [
      "NVIDIA TensorRT (2017): ≈ 90% datacenter GPU share. Compiles per generation (Volta, Ampere, Hopper, Blackwell). Total lock-in.",
      "Apple CoreML (2017): only way to use the Neural Engine. No export path to Android. Private on-device inference.",
      "Google TFLite (2017): Android dominates global mobile. Tuned for ARM Cortex and Pixel TPU. < 10 ms latency.",
      "Meta ExecuTorch (2024): ships Quest, Ray-Ban, future AR. PyTorch on-device without cloud.",
      "Each has a strategic reason. UMC converts across all, without favoritism.",
    ]),
  P("cas-usage-secteurs", "Industries", 11,
    "Cas d'usage d'UMC par secteur",
    "UMC use cases by industry",
    "Santé, finance, automobile, défense : pourquoi chacun a besoin de conversions certifiées.",
    "Health, finance, automotive, defense: why each needs certified conversions.",
    [],
    [
      "Santé : un modèle de diagnostic radiologique doit être déployé sur scanners GE, Siemens, Philips — chacun avec son SDK. UMC fournit le certificat FDA.",
      "Finance : scoring de crédit, détection de fraude, trading algo. Bâle III impose une traçabilité du modèle déployé.",
      "Automobile : ADAS et conduite autonome. Tesla, BMW convertissent vers TensorRT (cabine) et OpenVINO (passerelles). ISO 26262.",
      "Défense : drones, sonar, satellites. Conversion RKNN, QNN, matériels classifiés. Le certificat ed25519 prouve l'absence de manipulation.",
      "Divertissement : recommandations Netflix, Spotify ; mocap cinéma. Conversion ONNX pour multi-cloud.",
    ],
    [
      "Health: radiology model deployed on GE, Siemens, Philips scanners. UMC provides FDA-required certificate.",
      "Finance: credit scoring, fraud, algo trading. Basel III demands deployed-model traceability.",
      "Automotive: ADAS and autonomous driving. Tesla, BMW convert to TensorRT (cabin) and OpenVINO (gateways). ISO 26262.",
      "Defense: drones, sonar, satellites. RKNN, QNN, classified hardware. ed25519 proves no tampering.",
      "Entertainment: Netflix, Spotify recommendation; film mocap. ONNX for multi-cloud.",
    ]),
  P("awq-vs-gptq-vs-gguf", "Comparaison", 9,
    "AWQ vs GPTQ vs GGUF : quel format quantifié choisir",
    "AWQ vs GPTQ vs GGUF: which quantized format to pick",
    "Trois approches, trois cibles, trois compromis.",
    "Three approaches, three targets, three trade-offs.",
    [],
    [
      "AWQ : activation-aware, idéal GPU. INT8 sur colonnes saillantes, INT4 ailleurs. Préférez AWQ pour l'inférence GPU haut-débit.",
      "GPTQ : Hessien approximé, rapide à produire, large support communautaire Hugging Face.",
      "GGUF (Q4_K_M, Q5_K_S, Q8_0) : format llama.cpp, optimal CPU et inférence locale. Standard de fait pour les LLM locaux.",
      "Benchmark Llama 3 8B sur MMLU : FP16 = 68,4 ; AWQ INT4 = 67,9 ; GPTQ INT4 = 67,2 ; GGUF Q4_K_M = 67,6.",
      "Conclusion : AWQ pour la production GPU, GGUF Q4_K_M pour le local, GPTQ pour les expérimentations.",
    ],
    [
      "AWQ: activation-aware, ideal on GPU. INT8 for salient columns, INT4 elsewhere. Prefer AWQ for high-throughput GPU inference.",
      "GPTQ: approximated Hessian, fast to produce, broad Hugging Face community support.",
      "GGUF (Q4_K_M, Q5_K_S, Q8_0): llama.cpp format, optimal for CPU and local inference.",
      "Benchmark Llama 3 8B on MMLU: FP16 = 68.4; AWQ INT4 = 67.9; GPTQ INT4 = 67.2; GGUF Q4_K_M = 67.6.",
      "Conclusion: AWQ for GPU production, GGUF Q4_K_M for local, GPTQ for experiments.",
    ]),
  P("fp8-nouveau-standard", "Précision", 8,
    "Le nouveau standard FP8 : E4M3, E5M2, Hopper, Blackwell",
    "The new FP8 standard: E4M3, E5M2, Hopper, Blackwell",
    "Pourquoi FP8 remplace FP16 sur les GPU récents et comment UMC le gère.",
    "Why FP8 replaces FP16 on recent GPUs and how UMC handles it.",
    [],
    [
      "FP8 divise la mémoire par 2 vs FP16, double le débit Tensor Cores sur Hopper (H100, H200) et Blackwell (B100, B200).",
      "Deux variantes : E4M3 (4 exposant, 3 mantisse) pour les activations, E5M2 (5/2) pour les gradients.",
      "OpenAI, Anthropic, Meta entraînent en FP8 mixed-precision. Perte vs BF16 < 0,1 point sur MMLU.",
      "UMC convertit BF16 → FP8 (E4M3) avec calibration automatique sur 128 séquences. Échelle par tenseur stockée dans le certificat.",
    ],
    [
      "FP8 halves memory vs FP16, doubles Tensor Cores throughput on Hopper (H100, H200) and Blackwell (B100, B200).",
      "Two variants: E4M3 for activations, E5M2 for gradients.",
      "OpenAI, Anthropic, Meta now train in FP8 mixed-precision. Loss vs BF16 < 0.1 point on MMLU.",
      "UMC converts BF16 → FP8 (E4M3) with automatic calibration on 128 sequences. Per-tensor scale stored in the certificate.",
    ]),
  P("umc-modele-economique", "Entreprise", 7,
    "UMC et son modèle économique : pourquoi payer pour un service universel",
    "UMC's economics: why pay for a universal service",
    "Comment l'abonnement finance la R&D, les serveurs, le support des 32 formats.",
    "How subscriptions fund R&D, servers, support of 32 formats.",
    [],
    [
      "Maintenir le support de 32 formats coûte cher. Chaque mise à jour de TensorRT, CoreML, TFLite casse potentiellement les conversions existantes.",
      "Les serveurs GPU (A100, H100) consomment de l'énergie. Un Llama 405B en TensorRT-LLM mobilise 8 H100 pendant 4 minutes.",
      "La certification cryptographique exige une infrastructure HSM pour les clés ed25519 racines.",
      "Tarification : Free (10 conversions/mois), pay-as-you-go (1 à 3 € par conversion), Pro 19 €/mois (illimité), Enterprise sur devis.",
      "Pourquoi payer ? Recoder ces pipelines en interne coûte 34 semaines/an par équipe de 8 ingénieurs. Le ROI d'UMC est immédiat.",
    ],
    [
      "Maintaining 32 formats is expensive. Every TensorRT, CoreML, TFLite update potentially breaks conversions.",
      "GPU servers (A100, H100) burn energy. A Llama 405B TensorRT-LLM compile ties 8 H100s for 4 minutes.",
      "Cryptographic certification requires HSM infrastructure for ed25519 root keys.",
      "Pricing: Free (10/month), pay-as-you-go (€1–3 per conversion), Pro €19/month (unlimited), Enterprise on quote.",
      "Why pay? Rebuilding these pipelines in-house costs 34 weeks/year per 8-engineer team. UMC ROI is immediate.",
    ]),
];